packages:
  - 'apps/*'
  - 'packages/*'
  - 'e2e'
publicHoistPattern:
  - '*prisma*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  prisma: true
overrides:
  zod: ^3.25.76
